name: Using Actions
on: 
  push:
  #exemples of pull request types:
  #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  pull_request:
    types:
      - "closed"
      - "assigned"
      - "opened"
      - "reopened"
  schedule:
    - cron: "* * * * *"
    #min - hour - day- month - day(week)

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: List Files
        run: |
          pwd
          ls
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token}}
          echo $GITHUB_TOKEN
          echo "this is the branch that treiggered workflow: $GITHUB_REF"

  
      - name: Simple JS Action
        id: greet #to reference this step in other, we need provide a id name
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Matheus
      
      - name: Log Greeting Time from previously action
        run: echo "${{ steps.greet.outputs.time }}"