name: Matrix job
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,10]
      max-parallel: 2
     runs-on: {{ matrix.os}}

     steps:
      - name: Log node version
        run: node -v
      
      - uses: actions/setup-node@v2.1.3
        with:
          node_version: ${{ matrix.node_version }}
      
      - name: Log node version
        run: node -v