name: Matrix job
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]
        include:
          - os: ubuntu-latest
            node-version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}

    steps:
     - name: Log node version
       run: node -v
     
     - uses: actions/setup-node@v2.1.3
       with:
         node_version: ${{ matrix.node-version }}
     
     - name: Log node version
       run: node -v